INSERT INTO countries (id_country, country,  region, subregion) VALUES
(1,  'Afghanistan',  'Asia',  'Southern Asia'),
(2,  'Aland Islands',  'Europe',  'Northern Europe'),
(3,  'Albania',  'Europe',  'Southern Europe'),
(4,  'Algeria',  'Africa',  'Northern Africa'),
(5,  'American Samoa',  'Oceania',  'Polynesia'),
(6,  'Andorra',  'Europe',  'Southern Europe'),
(7,  'Angola',  'Africa',  'Middle Africa'),
(8,  'Anguilla',  'Americas',  'Caribbean'),
(10,  'Antigua And Barbuda',  'Americas',  'Caribbean'),
(11,  'Argentina',  'Americas',  'South America'),
(12,  'Armenia',  'Asia',  'Western Asia'),
(13,  'Aruba',  'Americas',  'Caribbean'),
(14,  'Australia',  'Oceania',  'Australia and New Zealand'),
(15,  'Austria',  'Europe',  'Western Europe'),
(16,  'Azerbaijan',  'Asia',  'Western Asia'),
(17,  'Bahamas The',  'Americas',  'Caribbean'),
(18,  'Bahrain',  'Asia',  'Western Asia'),
(19,  'Bangladesh',  'Asia',  'Southern Asia'),
(20,  'Barbados',  'Americas',  'Caribbean'),
(21,  'Belarus',  'Europe',  'Eastern Europe'),
(22,  'Belgium',  'Europe',  'Western Europe'),
(23,  'Belize',  'Americas',  'Central America'),
(24,  'Benin',  'Africa',  'Western Africa'),
(25,  'Bermuda',  'Americas',  'Northern America'),
(26,  'Bhutan',  'Asia',  'Southern Asia'),
(27,  'Bolivia',  'Americas',  'South America'),
(28,  'Bosnia and Herzegovina',  'Europe',  'Southern Europe'),
(29,  'Botswana',  'Africa',  'Southern Africa'),
(31,  'Brazil',  'Americas',  'South America'),
(32,  'British Indian Ocean Territory',  'Africa',  'Eastern Africa'),
(33,  'Brunei',  'Asia',  'South-Eastern Asia'),
(34,  'Bulgaria',  'Europe',  'Eastern Europe'),
(35,  'Burkina Faso',  'Africa',  'Western Africa'),
(36,  'Burundi',  'Africa',  'Eastern Africa'),
(37,  'Cambodia',  'Asia',  'South-Eastern Asia'),
(38,  'Cameroon',  'Africa',  'Middle Africa'),
(39,  'Canada',  'Americas',  'Northern America'),
(40,  'Cape Verde',  'Africa',  'Western Africa'),
(41,  'Cayman Islands',  'Americas',  'Caribbean'),
(42,  'Central African Republic',  'Africa',  'Middle Africa'),
(43,  'Chad',  'Africa',  'Middle Africa'),
(44,  'Chile',  'Americas',  'South America'),
(45,  'China',  'Asia',  'Eastern Asia'),
(46,  'Christmas Island',  'Oceania',  'Australia and New Zealand'),
(47,  'Cocos (Keeling) Islands',  'Oceania',  'Australia and New Zealand'),
(48,  'Colombia',  'Americas',  'South America'),
(49,  'Comoros',  'Africa',  'Eastern Africa'),
(50,  'Congo',  'Africa',  'Middle Africa'),
(52,  'Cook Islands',  'Oceania',  'Polynesia'),
(53,  'Costa Rica',  'Americas',  'Central America'),
(54,  'Cote DIvoire (Ivory Coast)',  'Africa',  'Western Africa'),
(55,  'Croatia',  'Europe',  'Southern Europe'),
(56,  'Cuba',  'Americas',  'Caribbean'),
(57,  'Cyprus',  'Europe',  'Southern Europe'),
(58,  'Czech Republic',  'Europe',  'Eastern Europe'),
(59,  'Denmark',  'Europe',  'Northern Europe'),
(60,  'Djibouti',  'Africa',  'Eastern Africa'),
(61,  'Dominica',  'Americas',  'Caribbean'),
(62,  'Dominican Republic',  'Americas',  'Caribbean'),
(63,  'East Timor',  'Asia',  'South-Eastern Asia'),
(64,  'Ecuador',  'Americas',  'South America'),
(65,  'Egypt',  'Africa',  'Northern Africa'),
(66,  'El Salvador',  'Americas',  'Central America'),
(67,  'Equatorial Guinea',  'Africa',  'Middle Africa'),
(68,  'Eritrea',  'Africa',  'Eastern Africa'),
(69,  'Estonia',  'Europe',  'Northern Europe'),
(70,  'Ethiopia',  'Africa',  'Eastern Africa'),
(71,  'Falkland Islands',  'Americas',  'South America'),
(72,  'Faroe Islands',  'Europe',  'Northern Europe'),
(73,  'Fiji Islands',  'Oceania',  'Melanesia'),
(74,  'Finland',  'Europe',  'Northern Europe'),
(75,  'France',  'Europe',  'Western Europe'),
(76,  'French Guiana',  'Americas',  'South America'),
(77,  'French Polynesia',  'Oceania',  'Polynesia'),
(78,  'French Southern Territories',  'Africa',  'Southern Africa'),
(79,  'Gabon',  'Africa',  'Middle Africa'),
(80,  'Gambia The',  'Africa',  'Western Africa'),
(81,  'Georgia',  'Asia',  'Western Asia'),
(82,  'Germany',  'Europe',  'Western Europe'),
(83,  'Ghana',  'Africa',  'Western Africa'),
(84,  'Gibraltar',  'Europe',  'Southern Europe'),
(85,  'Greece',  'Europe',  'Southern Europe'),
(86,  'Greenland',  'Americas',  'Northern America'),
(87,  'Grenada',  'Americas',  'Caribbean'),
(88,  'Guadeloupe',  'Americas',  'Caribbean'),
(89,  'Guam',  'Oceania',  'Micronesia'),
(90,  'Guatemala',  'Americas',  'Central America'),
(91,  'Guernsey and Alderney',  'Europe',  'Northern Europe'),
(92,  'Guinea',  'Africa',  'Western Africa'),
(93,  'Guinea-Bissau',  'Africa',  'Western Africa'),
(94,  'Guyana',  'Americas',  'South America'),
(95,  'Haiti',  'Americas',  'Caribbean'),
(97,  'Honduras',  'Americas',  'Central America'),
(98,  'Hong Kong S.A.R.',  'Asia',  'Eastern Asia'),
(99,  'Hungary',  'Europe',  'Eastern Europe'),
(100,  'Iceland',  'Europe',  'Northern Europe'),
(101,  'India',  'Asia',  'Southern Asia'),
(102,  'Indonesia',  'Asia',  'South-Eastern Asia'),
(103,  'Iran',  'Asia',  'Southern Asia'),
(104,  'Iraq',  'Asia',  'Western Asia'),
(105,  'Ireland',  'Europe',  'Northern Europe'),
(106,  'Israel',  'Asia',  'Western Asia'),
(107,  'Italy',  'Europe',  'Southern Europe'),
(108,  'Jamaica',  'Americas',  'Caribbean'),
(109,  'Japan',  'Asia',  'Eastern Asia'),
(110,  'Jersey',  'Europe',  'Northern Europe'),
(111,  'Jordan',  'Asia',  'Western Asia'),
(112,  'Kazakhstan',  'Asia',  'Central Asia'),
(113,  'Kenya',  'Africa',  'Eastern Africa'),
(114,  'Kiribati',  'Oceania',  'Micronesia'),
(115,  'North Korea',  'Asia',  'Eastern Asia'),
(116,  'South Korea',  'Asia',  'Eastern Asia'),
(117,  'Kuwait',  'Asia',  'Western Asia'),
(118,  'Kyrgyzstan',  'Asia',  'Central Asia'),
(119,  'Laos',  'Asia',  'South-Eastern Asia'),
(120,  'Latvia',  'Europe',  'Northern Europe'),
(121,  'Lebanon',  'Asia',  'Western Asia'),
(122,  'Lesotho',  'Africa',  'Southern Africa'),
(123,  'Liberia',  'Africa',  'Western Africa'),
(124,  'Libya',  'Africa',  'Northern Africa'),
(125,  'Liechtenstein',  'Europe',  'Western Europe'),
(126,  'Lithuania',  'Europe',  'Northern Europe'),
(127,  'Luxembourg',  'Europe',  'Western Europe'),
(128,  'Macau S.A.R.',  'Asia',  'Eastern Asia'),
(129,  'Macedonia',  'Europe',  'Southern Europe'),
(130,  'Madagascar',  'Africa',  'Eastern Africa'),
(131,  'Malawi',  'Africa',  'Eastern Africa'),
(132,  'Malaysia',  'Asia',  'South-Eastern Asia'),
(133,  'Maldives',  'Asia',  'Southern Asia'),
(134,  'Mali',  'Africa',  'Western Africa'),
(135,  'Malta',  'Europe',  'Southern Europe'),
(136,  'Man (Isle of)',  'Isle of Man',  'Europe'),
(137,  'Marshall Islands',  'Oceania',  'Micronesia'),
(138,  'Martinique',  'Americas',  'Caribbean'),
(139,  'Mauritania',  'Africa',  'Western Africa'),
(140,  'Mauritius',  'Africa',  'Eastern Africa'),
(141,  'Mayotte',  'Africa',  'Eastern Africa'),
(142,  'Mexico',  'Americas',  'Central America'),
(143,  'Micronesia',  'Oceania',  'Micronesia'),
(144,  'Moldova',  'Europe',  'Eastern Europe'),
(145,  'Monaco',  'Europe',  'Western Europe'),
(146,  'Mongolia',  'Asia',  'Eastern Asia'),
(147,  'Montenegro',  'Europe',  'Southern Europe'),
(148,  'Montserrat',  'Americas',  'Caribbean'),
(149,  'Morocco',  'Africa',  'Northern Africa'),
(150,  'Mozambique',  'Africa',  'Eastern Africa'),
(151,  'Myanmar',  'Asia',  'South-Eastern Asia'),
(152,  'Namibia',  'Africa',  'Southern Africa'),
(153,  'Nauru',  'Oceania',  'Micronesia'),
(154,  'Nepal',  'Asia',  'Southern Asia'),
(156,  'Netherlands',  'Europe',  'Western Europe'),
(157,  'New Caledonia',  'Oceania',  'Melanesia'),
(158,  'New Zealand',  'Oceania',  'Australia and New Zealand'),
(159,  'Nicaragua',  'Americas',  'Central America'),
(160,  'Niger',  'Africa',  'Western Africa'),
(161,  'Nigeria',  'Africa',  'Western Africa'),
(162,  'Niue',  'Oceania',  'Polynesia'),
(163,  'Norfolk Island',  'Oceania',  'Australia and New Zealand'),
(164,  'Northern Mariana Islands',  'Oceania',  'Micronesia'),
(165,  'Norway',  'Europe',  'Northern Europe'),
(166,  'Oman',  'Asia',  'Western Asia'),
(167,  'Pakistan',  'Asia',  'Southern Asia'),
(168,  'Palau',  'Oceania',  'Micronesia'),
(169,  'Palestinian Territory Occupied',  'Asia',  'Western Asia'),
(170,  'Panama',  'Americas',  'Central America'),
(171,  'Papua new Guinea',  'Oceania',  'Melanesia'),
(172,  'Paraguay',  'Americas',  'South America'),
(173,  'Peru',  'Americas',  'South America'),
(174,  'Philippines',  'Asia',  'South-Eastern Asia'),
(175,  'Pitcairn Island',  'Oceania',  'Polynesia'),
(176,  'Poland',  'Europe',  'Eastern Europe'),
(177,  'Portugal',  'Europe',  'Southern Europe'),
(178,  'Puerto Rico',  'Americas',  'Caribbean'),
(179,  'Qatar',  'Asia',  'Western Asia'),
(180,  'Reunion',  'Africa',  'Eastern Africa'),
(181,  'Romania',  'Europe',  'Eastern Europe'),
(182,  'Russia',  'Europe',  'Eastern Europe'),
(183,  'Rwanda',  'Africa',  'Eastern Africa'),
(184,  'Saint Helena',  'Africa',  'Western Africa'),
(185,  'Saint Kitts And Nevis',  'Americas',  'Caribbean'),
(186,  'Saint Lucia',  'Americas',  'Caribbean'),
(187,  'Saint Pierre and Miquelon',  'Americas',  'Northern America'),
(189,  'Saint-Barthelemy',  'Americas',  'Caribbean'),
(190,  'Saint-Martin (French part)',  'Americas',  'Caribbean'),
(191,  'Samoa',  'Oceania',  'Polynesia'),
(192,  'San Marino',  'Europe',  'Southern Europe'),
(193,  'Sao Tome and Principe',  'Africa',  'Middle Africa'),
(194,  'Saudi Arabia',  'Asia',  'Western Asia'),
(195,  'Senegal',  'Africa',  'Western Africa'),
(196,  'Serbia',  'Europe',  'Southern Europe'),
(197,  'Seychelles',  'Africa',  'Eastern Africa'),
(198,  'Sierra Leone',  'Africa',  'Western Africa'),
(199,  'Singapore',  'Asia',  'South-Eastern Asia'),
(200,  'Slovakia',  'Europe',  'Eastern Europe'),
(201,  'Slovenia',  'Europe',  'Southern Europe'),
(202,  'Solomon Islands',  'Oceania',  'Melanesia'),
(203,  'Somalia',  'Africa',  'Eastern Africa'),
(204,  'South Africa',  'Africa',  'Southern Africa'),
(205,  'South Georgia',  'Americas',  'South America'),
(206,  'South Sudan',  'Africa',  'Middle Africa'),
(207,  'Spain',  'Europe',  'Southern Europe'),
(208,  'Sri Lanka',  'Asia',  'Southern Asia'),
(209,  'Sudan',  'Africa',  'Northern Africa'),
(210,  'Suriname',  'Americas',  'South America'),
(211,  'Svalbard And Jan Mayen Islands',  'Europe',  'Northern Europe'),
(212,  'Swaziland',  'Africa',  'Southern Africa'),
(213,  'Sweden',  'Europe',  'Northern Europe'),
(214,  'Switzerland',  'Europe',  'Western Europe'),
(215,  'Syria',  'Asia',  'Western Asia'),
(216,  'Taiwan',  'Asia',  'Eastern Asia'),
(217,  'Tajikistan',  'Asia',  'Central Asia'),
(218,  'Tanzania',  'Africa',  'Eastern Africa'),
(219,  'Thailand',  'Asia',  'South-Eastern Asia'),
(220,  'Togo',  'Africa',  'Western Africa'),
(221,  'Tokelau',  'Oceania',  'Polynesia'),
(222,  'Tonga',  'Oceania',  'Polynesia'),
(223,  'Trinidad And Tobago',  'Americas',  'Caribbean'),
(224,  'Tunisia',  'Africa',  'Northern Africa'),
(225,  'Turkey',  'Asia',  'Western Asia'),
(226,  'Turkmenistan',  'Asia',  'Central Asia'),
(227,  'Turks And Caicos Islands',  'Americas',  'Caribbean'),
(228,  'Tuvalu',  'Oceania',  'Polynesia'),
(229,  'Uganda',  'Africa',  'Eastern Africa'),
(230,  'Ukraine',  'Europe',  'Eastern Europe'),
(231,  'United Arab Emirates',  'Asia',  'Western Asia'),
(232,  'United Kingdom',  'Europe',  'Northern Europe'),
(233,  'United States',  'Americas',  'Northern America'),
(235,  'Uruguay',  'Americas',  'South America'),
(236,  'Uzbekistan',  'Asia',  'Central Asia'),
(237,  'Vanuatu',  'Oceania',  'Melanesia'),
(238,  'Vatican City State (Holy See)',  'Europe',  'Southern Europe'),
(239,  'Venezuela',  'Americas',  'South America'),
(240,  'Vietnam',  'Asia',  'South-Eastern Asia'),
(241,  'Virgin Islands (British)',  'Americas',  'Caribbean'),
(242,  'Virgin Islands (US)',  'Americas',  'Caribbean'),
(243,  'Wallis And Futuna Islands',  'Oceania',  'Polynesia'),
(244,  'Western Sahara',  'Africa',  'Northern Africa'),
(245,  'Yemen',  'Asia',  'Western Asia'),
(246,  'Zambia',  'Africa',  'Eastern Africa'),
(247,  'Zimbabwe',  'Africa',  'Eastern Africa'),
(248,  'Kosovo',  'Europe',  'Eastern Europe'),
(249,  'Curaçao',  'Americas',  'Caribbean'),
(250,  'Sint Maarten (Dutch part)',  'Americas',  'Caribbean');